#!/usr/bin/env php
<?php

require_once  dirname(__DIR__) . '/vendor/autoload.php';

$client = new GuzzleHttp\Client();

$baseUrl = 'https://notts-digital.pavlakis.info/index.php?group=';

$client = new \GuzzleHttp\Client();

$groups = include(dirname(__DIR__) . '/app/configs/groups.php');

if (array_key_exists('meetups', $groups)) {
    $meetupGroups = $groups['meetups'];
    foreach ($meetupGroups as $meetup => $meetupInfo) {
        try {
            $url = $baseUrl . urlencode($meetup);
            $client->request('GET', $url);
            sleep(1);
        } catch (\Exception $e) {
            continue;
        } catch (\GuzzleHttp\Exception\GuzzleException $e) {
            continue;
        }
    }
}