name: CI
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v2
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: Setup composer
        run:  composer install --prefer-dist --no-progress --no-suggest
      - name: run phpunit
        run:  composer test-docs
      - name: run static analysis
        run:  composer run-static-analysis